apiVersion: v1
kind: Service
metadata:
  name: nav7-fe-service
  namespace: sk-team-07
spec:
  type: ClusterIP
  selector:
    app: nav7-fe
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
